[package]
name = "learn-bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3